<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>edu.umd.lib</groupId>
  <artifactId>umd-fcrepo-webapp</artifactId>
  <packaging>war</packaging>
  <version>3.0.0-SNAPSHOT</version>
  <name>UMD Libraries Fedora Web Application</name>
  <url>https://github.com/umd-lib/umd-fcrepo-webapp</url>

  <properties>
    <build.timestamp>${maven.build.timestamp}</build.timestamp>
    <cas-client.version>4.1.0</cas-client.version>
    <commons-validator.version>1.7</commons-validator.version>
    <commons-lang3.version>3.20.0</commons-lang3.version>
    <fcrepo.version>7.0.0</fcrepo.version>
    <jakarta-annotation.version>2.1.1</jakarta-annotation.version>
    <jakarta-servlet.version>6.1.0</jakarta-servlet.version>
    <jersey.version>4.0.2</jersey.version>
    <jjwt.version>0.12.6</jjwt.version>
    <junit.version>4.13.1</junit.version>
    <ldaptive.version>1.2.4</ldaptive.version>
    <!-- maven.build.timestamp.format>yyyy-MM-dd</maven.build.timestamp.format -->
    <maven.compiler.source>25</maven.compiler.source>
    <maven.compiler.target>25</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spring.version>6.2.19</spring.version>
    <spring-security.version>7.0.6</spring-security.version>
    <warFileName>${project.artifactId}-${project.version}</warFileName>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.fcrepo</groupId>
      <artifactId>fcrepo-webapp</artifactId>
      <version>${fcrepo.version}</version>
      <type>war</type>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>${jakarta-servlet.version}</version>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <version>${jakarta-annotation.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <version>${spring.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-web</artifactId>
      <version>${spring-security.version}</version>
    </dependency>

    <dependency>
      <groupId>org.glassfish.jersey.core</groupId>
      <artifactId>jersey-common</artifactId>
      <version>${jersey.version}</version>
    </dependency>

    <dependency>
      <groupId>commons-validator</groupId>
      <artifactId>commons-validator</artifactId>
      <version>${commons-validator.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${commons-lang3.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apereo.cas.client</groupId>
      <artifactId>cas-client-core</artifactId>
      <version>${cas-client.version}</version>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-api</artifactId>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-impl</artifactId>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-jackson</artifactId>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <groupId>org.ldaptive</groupId>
      <artifactId>ldaptive</artifactId>
      <version>${ldaptive.version}</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-test</artifactId>
      <version>${spring.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>${warFileName}</finalName>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <overlays>
            <overlay>
              <groupId>org.fcrepo</groupId>
              <artifactId>fcrepo-webapp</artifactId>
              <!-- excludes>
                <exclude>WEB-INF/no-auth-web.xml</exclude>
                <exclude>WEB-INF/classes/logback.xml</exclude>
                <exclude>WEB-INF/classes/namespaces.yml</exclude>
                <exclude>favicon.ico</exclude>
              </excludes -->
            </overlay>
          </overlays>
          <webResources>
            <resource>
              <directory>src/main/webapp</directory>
              <filtering>true</filtering>
              <includes>
                <include>index.html</include>
              </includes>
            </resource>
          </webResources>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.2.0</version>
        <dependencies>
          <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>12.5</version>
          </dependency>
        </dependencies>
        <configuration>
          <target>
            <xslt in="src/main/webapp/WEB-INF/web.xml" out="docs/ServletFilters.puml" style="src/xslt/webdoc.xsl">
              <factory name="net.sf.saxon.BasicTransformerFactory"/>
            </xslt>
          </target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
